#pragma once 

namespace IDs {

    enum class IDs {
        vazio = 0,
        jogador,
        espada_jogador,
        espada_inimigo,
        projetil_inimigo,
        esqueleto,
        minotauro,
        alma,
        plataforma,
        caixa,
        moeda_amarela,
        moeda_cinza,
        vida,
        fundo_florestaNegra,
        fundo_florestaBranca,
        fase_florestaBranca,
        fundo_florestaVermelha,
        fase_florestaVermelha,
        jogar_florestaVermelha,
        jogar_florestaBranca,
        botao_novoJogo,
        botao_carregarJogo,
        botao_salvarJogada,
        botao_colocacao,
        botao_opcao,
        botao_sair,
        botao_voltar,
        botao_volume_geral,
        botao_volume_jogo,
        botao_volume_menu,
        botao_esquerda,
        botao_direita,
        botao_salvar_colocacao,
        menu_principal,
        menu_pausa,
        menu_opcao,
        menu_carregar_jogo,
        menu_colocacao,
        menu_game_over,
        estado_menu_principal,
        estado_menu_pausa,
        estado_menu_opcaoPrincipal,
        estado_menu_carregar_jogo,
        estado_menu_colocacao,
        estado_menu_game_over,
    };

}